language: node_js
node_js:
  - 10
branches:
  only:
    - source
script:
  - yarn build
  - cp CNAME public/
  - cd public
  - git init
  - git add .
  - git commit -m "Updated website."
  - git push https://fmoliveira:$GITHUB_TOKEN@github.com/fmoliveira/fmoliveira.github.io.git master --force
