# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Filipe Oliveira
email: contato@fmoliveira.com.br
description: > # this means to ignore newlines until "baseurl:"
  Filipe Oliveira is a Fullstack JavaScript Engineer from Campinas, Brazil.
  He likes Linux, Zsh, ES6, Node.js, Angular, MongoDB, Docker,
  and lots of other amazing stuff.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://fmoliveira.com.br" # the base hostname & protocol for your site
twitter_username: tfmoliveira
github_username:  fmoliveira

# Build settings
markdown: kramdown
