title: Filipe Oliveira
email: contato@fmoliveira.com.br
description: >
  Engenheiro de Software e Empreendedor apaixonado por disseminar conhecimento
  e aprender coisas novas o tempo todo. Gosto de escrever sobre JavaScript,
  React, Linux, automação de processos e produtividade.
url: "https://fmoliveira.com.br"
twitter_username: tfmoliveira
github_username:  fmoliveira

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
